version: '3'
services:
  web:
    build: .
    ports:
      - 8080:8080
    environment:
      PORT: 8080
      MONGODB_URI: mongodb://root:MongoDB123@mongodb:27017
      JWT_SECRET: fdsfdfgwergrejkt
    links:
      - mongodb
    volumes:
      - ./app:/home/node/app
    command: sh -c "npm install && npm start"
  mongodb:
    image: mongo:4.4
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: MongoDB123
    ports:
      - "27017:27017"
    volumes:
      - ./mongodb:/data/db